config/routes.rb
Rails.application.routes.draw do

  resources :courses
  get "/courses" => "courses#index"
  get "/courses/:id" => "courses#show"

  resources :users
  root "users#new"
  post "/signup" => "users#create"
  get "/users/:id/edit" => "users#edit"
  put "/users/:id" => "users#update"

  resources :teetimes
  get "/teetimes/:id" => "teetimes#show"

  resources :reservations
  post "/teetimes/:id" => "reservations#create"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  

end

app/models/course.rb
class Course < ActiveRecord::Base

def self.search(query)
	where("city like ?", "%#{query}%")
	where("name like ?", "%#{query}%")
end


end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :teetime
end

app/models/teetime.rb
class Teetime < ActiveRecord::Base
	has_many :users
	has_many :reservations
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :teetime
	has_many :reservations
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
def index
    @courses = Course.all	
  if params[:search]
    @courses = Course.search(params[:search]).order("created_at DESC")
  else
    @courses = Course.all.order('created_at DESC')
  end
end
 
def show
    @course = Course.find(params[:id])
    @teetimes = Teetime.all
    # binding.pry
end
 
  # def new
  #   @courses = Courses.new
  # end
 
  # def create
  #   @courses = Courses.new(Courses_params)
 
  #   if @Courses.save
  #     redirect_to @Courses
  #   else
  #     render 'new'
  #   end
  # end
 
  # def edit
  #   @courses = Courses.find(params[:id])
  # end

  # def update
  #   @courses = Courses.find(params[:id])
 
  #   if @courses.update(courses_params)
  #     redirect_to @Courses
  #   else
  #     render 'edit'
  #   end
  # end
 
  # def destroy
  #   @courses = Courses.find(params[:id])
  #   @courses.destroy
 
  #   redirect_to coursess_path
  # end
 
  private
    def courses_params
      params.require(:courses).permit(:name, :address, :city, :classification, :price, :phone, :img)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	
	def create
	   @reservation = Reservation.new(reservations_params)
    if @reservation.save
      redirect_to "/courses"
    else
      redirect_to "/"
    end
  end
	
	private
    def reservations_params
      params.require(:reservation).permit(:name, :comments, :teetime_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
  	user = User.find_by_email(params[:session][:email])
  		if user && user.authenticate(params[:session][:password])
    		session[:user_id] = user.id
    		redirect_to '/courses'
  		else
    		redirect_to '/login'
  		end 
	end
  
  	def destroy
      binding.pry
  		session[:user_id] = nil 
 	 	  redirect_to '/' 
	  end

end

app/controllers/teetimes_controller.rb
class TeetimesController < ApplicationController
	def show
		@teetimes = Teetime.all
		@teetime = Teetime.find_by_id(params[:id])
		@reservation = Reservation.new
		@reservations = Reservation.all
		@user = User.all
		# binding.pry
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/courses"
    else
      redirect_to "/"
    end
  end

  # def edit
  #   @user = current_user
  # end

  # def update
  #   @user = User.find(params[:id])
  #   if @user.update_attributes(user_params)
  #     # Handle a successful update.
  #   else
  #     render 'edit'
  #   end
  # end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teetimes_helper.rb
module TeetimesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/index.html.erb
<button><%= link_to "Logout", "/" %></button>
<h1> FriendlyFour! </h1>

<h2> Search for a Long Island Golf Course by Name: </h2>

<div class="search">
<%= form_tag(courses_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Golf Courses" %>
  <%= submit_tag "Search", :name => nil%>
<% end %>
<br />

<% @courses.each do |course| %>
<div class="coursephoto" style="background-color:rgba(48, 71, 255, 0.5);">
<h3><%= course.name %> <h3/>
<h3><%= course.address %>, <%= course.city %> </h3>
<h3><%= course.phone %> </h3>
<h3><%= course.classification %> <%= course.price %> </h3>
<button> <%= link_to "More Info and Tee Times", course_path(course) %> </button>
</div>
<% end %>

</div>

app/views/courses/show.html.erb
<button><%= link_to "Logout", "/" %></button>
<button><%= link_to "Back", "/courses" %></button>
<h4><%= @course.name %></h4>

<div class="course">
<img src="<%= @course.img %>">
<p><%= @course.address %></p>
<p><%= @course.city %></p>
<p><%= @course.phone %></p>
<p><%= @course.price %> <%= @course.classification %> </p>

<h4> Choose a Tee Time Below: </h4>
</div>


<div class="bottom">
<select onChange="window.location.href=this.value">
<% @teetimes.each do |teetime| %>
<option value="<%= teetime_path(teetime) %>"><%= teetime.time %></option>
<% end %>
</select>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FriendlyFour</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/teetimes/show.html.erb
<button><%= link_to "Logout", "/" %></button>
<h1> <%= @teetime.time %> </h1>

<div class="ress">
<% if @reservations.find_by_teetime_id(@teetime.id) === nil %>
	<h2> Tee Time is Totally Open! </h2>
<% else %> 
	<% if @reservations.where(teetime_id: @teetime.id).count === 4 %>
	<h2> <%= @reservations.where(teetime_id: @teetime.id)[0].name %> </h2>
	<h3> <%= @reservations.where(teetime_id: @teetime.id)[0].comments %> </h3>
	<h2> <%= @reservations.where(teetime_id: @teetime.id)[1].name %> </h2>
	<h3> <%= @reservations.where(teetime_id: @teetime.id)[1].comments %> </h3>
	<h2> <%= @reservations.where(teetime_id: @teetime.id)[2].name %> </h2>
	<h3> <%= @reservations.where(teetime_id: @teetime.id)[2].comments %> </h3>
	<h2> <%= @reservations.where(teetime_id: @teetime.id)[3].name %> </h2>
	<h3> <%= @reservations.where(teetime_id: @teetime.id)[3].comments %> </h3>
	<% elsif @reservations.where(teetime_id: @teetime.id).count === 3 %>
	<h2> <%= @reservations.where(teetime_id: @teetime.id)[0].name %> </h2>
	<h3> <%= @reservations.where(teetime_id: @teetime.id)[0].comments %> </h3>
	<h2> <%= @reservations.where(teetime_id: @teetime.id)[1].name %> </h2>
	<h3> <%= @reservations.where(teetime_id: @teetime.id)[1].comments %> </h3>
	<h2> <%= @reservations.where(teetime_id: @teetime.id)[2].name %> </h2>
	<h3> <%= @reservations.where(teetime_id: @teetime.id)[2].comments %> </h3>
	<% elsif @reservations.where(teetime_id: @teetime.id).count === 2 %>
	<h2> <%= @reservations.where(teetime_id: @teetime.id)[0].name %> </h2>
	<h3> <%= @reservations.where(teetime_id: @teetime.id)[0].comments %> </h3>
	<h2> <%= @reservations.where(teetime_id: @teetime.id)[1].name %> </h2>
	<h3> <%= @reservations.where(teetime_id: @teetime.id)[1].comments %> </h3>
	<% else %>
	<h2> <%= @reservations.where(teetime_id: @teetime.id)[0].name %> </h2>
	<h3> <%= @reservations.where(teetime_id: @teetime.id)[0].comments %> </h3>
	<% end %>
<% end %>
</div>


<div class="teetime">

 <%= form_for(@reservation) do |f| %>  
  <div class="field"> 
    <%= f.label :name %> Confirmation<br> 
    <%= f.text_field :name %><br />
    <%= f.label :comments %> About Your Game <br />
    <%= f.text_field :comments %>
    <%= f.hidden_field :teetime_id, :value => @teetime.id %>
  </div>
  <br />
  <div class="actions"> 
    <button><%= f.submit "Book Time" %></button>
  </div> 
<% end %>
</div>

<br />
<button><%= link_to "Back To All Tee Times", "/courses" %></button>

app/views/users/edit.html.erb
<h1> Edit Profile </h1>

  <%= form_for (@user) do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name, :value => @user.name %><br />
  <%= f.label :email %>:
  <%= f.text_field :email, :value => @user.email %><br />
  <%= f.label :password %>:
  <%= f.password_field :password %><br />

  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<head>
    <meta charset="UTF-8">
    <title> Signup </title>
</head>

  <body>
  <h1> Welcome to FriendlyFour! </h1>
    <div class="wrap">
    <div class="avatar">
      <img src="http://us.cdn4.123rf.com/168nwm/chudtsankov/chudtsankov1307/chudtsankov130700014/20749046-lycklig-golfbolltecknad-tecken-vinka-f%C3%B6r-h%C3%A4lsning.jpg">
    </div>
  <%= form_for (@user) do |f| %>
  <%= f.text_field :name, :placeholder => "Name" %>
  <br />
  <%= f.text_field :email, :placeholder => "Email" %>
  <br />
  <%= f.password_field :password, :placeholder => "Password" %>
  <br />
  <button><%= f.submit %></button>
  <br />
  <br />
  <button><%= link_to "Already a User?", "/login" %></button>
  </div>
  <% end %>
 
 </body>